import {readFileSync, writeFileSync, readdirSync, statSync, mkdirSync} from 'node:fs'
import {join, dirname, resolve, relative} from 'node:path'
import {fileURLToPath} from 'node:url'

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..')
const srcRoot = join(root, 'src')
const outFile = join(root, 'docs', 'api-reference.md')

function walk(dir) {
	const out = []
	for (const name of readdirSync(dir).sort()) {
		if (name === 'shaders.gen.imba' || name === 'shaders.gen.mjs') continue
		const full = join(dir, name)
		const st = statSync(full)
		if (st.isDirectory()) out.push(...walk(full))
		else if (name.endsWith('.imba')) out.push(full)
	}
	return out
}

function extractProps(lines) {
	const props = []
	for (const line of lines) {
		const m = /^\s*prop\s+([A-Za-z_$][\w$]*)\s*(?:=\s*([^@]+?))?\s*(@watch)?\s*$/.exec(line)
		if (m) props.push({name: m[1], def: (m[2] || '').trim(), watch: !!m[3]})
		const g = /^\s*static\s+get\s+([A-Za-z_$][\w$]*)\s*$/.exec(line)
		if (g) props.push({name: `static ${g[1]}`, def: '(getter)', watch: false})
	}
	return props
}

function extractMethods(lines, exportedClasses) {
	const methods = new Map()
	let currentClass = null
	let classIndent = 0
	for (const line of lines) {
		const cm = /^export\s+class\s+([A-Za-z_$][\w$]*)/.exec(line)
		if (cm) {
			currentClass = cm[1]
			methods.set(currentClass, [])
			continue
		}
		const dm = /^\s+def\s+([A-Za-z_$][\w$]*)\s*(.*)$/.exec(line)
		if (dm && currentClass && !/^(constructor|render|mount|unmount|build)$/.test(dm[1])) {
			const sig = dm[2].trim()
			methods.get(currentClass).push({name: dm[1], sig})
		}
	}
	return methods
}

function describeFile(file) {
	const rel = relative(srcRoot, file)
	const lines = readFileSync(file, 'utf8').split('\n')
	const block = {file: rel, tags: [], exports: [], methods: new Map()}
	const propsByTag = new Map()
	let currentTag = null
	for (const line of lines) {
		const tm = /^tag\s+([a-z0-9-]+)/.exec(line)
		if (tm) {
			currentTag = tm[1]
			propsByTag.set(currentTag, [])
			continue
		}
		if (currentTag && /^\S/.test(line)) currentTag = null
		if (currentTag) {
			const pm = /^\s*prop\s+([A-Za-z_$][\w$]*)\s*(?:=\s*([^@]+?))?\s*(@watch)?\s*$/.exec(line)
			if (pm) propsByTag.get(currentTag).push({name: pm[1], def: (pm[2] || '').trim()})
		}
		const em = /^export\s+(?:default\s+)?(class|def|const|let)\s+([A-Za-z_$][\w$]*)\s*(.*)$/.exec(line)
		if (em) block.exports.push({kind: em[1], name: em[2], sig: em[3].trim()})
		const sm = /^export\s+class\s+([A-Za-z_$][\w$]*)/.exec(line)
		if (sm) block.methods.set(sm[1], [])
	}
	for (const [tag, props] of propsByTag) block.tags.push({name: tag, props})
	const clsMethods = extractMethods(lines)
	for (const [cls, list] of clsMethods) if (block.methods.has(cls)) block.methods.set(cls, list)
	return block
}

const files = walk(srcRoot)
const blocks = files.map(describeFile)

const out = []
out.push('# GlassKit API Reference')
out.push('')
out.push('Generated by tools/docgen.mjs from the source tree. Do not edit by hand — run `npm run docs`.')
out.push('')
out.push('## Entry points')
out.push('')
out.push('- ESM: `import GlassKit from "glasskit"`')
out.push('- CSS: `import "glasskit/css"`')
out.push('- IIFE: `<script src="dist/glasskit.js"></script>` exposes `window.GlassKit`')
out.push('')

const groups = new Map()
for (const b of blocks) {
	if (b.tags.length === 0 && b.exports.length === 0) continue
	const dir = b.file.split('/')[0]
	if (!groups.has(dir)) groups.set(dir, [])
	groups.get(dir).push(b)
}

for (const [group, list] of [...groups.entries()].sort()) {
	out.push(`## ${group}/`)
	out.push('')
	for (const b of list.sort((a, c) => a.file.localeCompare(c.file))) {
		out.push(`### ${b.file}`)
		out.push('')
		for (const tag of b.tags) {
			out.push(`Element \`<${tag.name}>\``)
			out.push('')
			if (tag.props.length > 0) {
				out.push('| property | default |')
				out.push('|---|---|')
				for (const p of tag.props) out.push(`| \`${p.name}\` | ${p.def ? `\`${p.def}\`` : '—'} |`)
				out.push('')
			}
		}
		for (const e of b.exports) {
			out.push(`- \`${e.kind} ${e.name}${e.sig && !e.sig.startsWith('{') ? ' ' + e.sig.split('\n')[0] : ''}\``)
		}
		for (const [cls, methods] of b.methods) {
			if (methods.length > 0) {
				out.push('')
				out.push(`\`${cls}\` methods:`)
				out.push('')
				for (const m of methods) out.push(`- \`${m.name}${m.sig ? ' ' + m.sig : ''}\``)
			}
		}
		out.push('')
	}
}

for (const b of blocks) {
	const shaderless = b
}
out.push('## Shader slot table (GlassParams, 12 × vec4 per shape)')
out.push('')
out.push('| slot | contents |')
out.push('|---|---|')
out.push('| v0 | rect (x, y, w, h) device px |')
out.push('| v1 | corner radii (tl, tr, br, bl) |')
out.push('| v2 | tint rgb + strength |')
out.push('| v3 | shadow (enabled, radius, offsetY, opacity) |')
out.push('| v4 | A: type, variant, tintStrength, interactive |')
out.push('| v5 | B: press, hover, pointerX, pointerY |')
out.push('| v6 | C: refraction, edge, chromatic, blur |')
out.push('| v7 | D: specularI, specularSharp, lumAdjust, dimming |')
out.push('| v8 | E: polySlot, superellipseN, polyCount, bevelExp |')
out.push('| v9 | F: alphaScale, reserved ×3 |')
out.push('| v10 | user slot |')
out.push('| v11 | user slot |')
out.push('')
out.push('PolyBlock: 8 polygon slots × 6 vec4 (12 control points each), binding 1. GlassBlock binding 0.')

mkdirSync(dirname(outFile), {recursive: true})
writeFileSync(outFile, out.join('\n') + '\n')
console.log(`[docgen] ${blocks.filter(b => b.tags.length + b.exports.length > 0).length} documented modules -> docs/api-reference.md`)
